LINK_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../win32/libs/)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../win32/includes/)

SET(OPENGL_LIBRARIES "opengl32.lib;glew32s.lib;glfw3.lib;glu32")
ADD_DEFINITIONS( -DGLEW_STATIC -D_CRT_SECURE_NO_WARNINGS)

SET(CMAKE_C_FLAGS                       "/W3 /MP")
SET(CMAKE_C_FLAGS_RELEASE               "/Ox /DNDEBUG")
SET(CMAKE_C_FLAGS_DEBUG                 "/Od /Ob0 /Zi")
SET(CMAKE_CXX_FLAGS                     "/W3 /MP")
SET(CMAKE_CXX_FLAGS_RELEASE             "/Ox /DNDEBUG")
SET(CMAKE_CXX_FLAGS_DEBUG               "/Od /Ob0 /Zi")

SET(CMAKE_EXE_LINKER_FLAGS_RELEASE      "/INCREMENTAL:NO")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG        "/DEBUG /INCREMENTAL")
