LINK_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../static/libs/)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../static/includes/)

SET(OPENGL_LIBRARIES    "-lGL")
SET(GLEW_LIBRARIES      "GLEW")
SET(GLFW_LIBRARIES      "-lglfw")
SET(ASSIMP_LIBRARIES    "-lassimp")
SET(DEVIL_LIBRARIES     "-lIL")
ADD_DEFINITIONS( -DGLEW_STATIC)
