LINK_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../static/libs/)
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/../static/includes/)

SET(OPENGL_LIBRARIES "GLEW -lglfw -lGL")
ADD_DEFINITIONS( -DGLEW_STATIC)
